name: PHP-FPM 7.4.3-4ubuntu2.8 on Ubuntu 20.04

on:
  push:
    branches: [ 7.4.3-4ubuntu2.8 ]
    tags:
      - '7.4.3-4ubuntu2.8-*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Print environment variables
        run: env
      - name: Build images
        run: |
          docker buildx build \
            --tag docker.io/raasss/php-fpm-ubuntu-20.04:${GITHUB_REF_NAME} \
            --tag docker.io/raasss/php-fpm-ubuntu-20.04:7.4.3-4ubuntu2.8 \
            --tag quay.io/raasss/php-fpm-ubuntu-20.04:${GITHUB_REF_NAME} \
            --tag quay.io/raasss/php-fpm-ubuntu-20.04:7.4.3-4ubuntu2.8 \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
      - name: Configure login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin docker.io
      - name: Configure login to Quay.io
        run: echo "${{ secrets.QUAY_PASSWORD }}" | docker login -u "${{ secrets.QUAY_USERNAME }}" --password-stdin quay.io
      - name: Push images
        run: |
          docker buildx build --push \
            --tag docker.io/raasss/php-fpm-ubuntu-20.04:${GITHUB_REF_NAME} \
            --tag docker.io/raasss/php-fpm-ubuntu-20.04:7.4.3-4ubuntu2.8 \
            --tag quay.io/raasss/php-fpm-ubuntu-20.04:${GITHUB_REF_NAME} \
            --tag quay.io/raasss/php-fpm-ubuntu-20.04:7.4.3-4ubuntu2.8 \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
      # - name: Save Docker build cache
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: docker-cache
      #     path: /var/lib/containers
